// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Chirp struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    sql.NullString
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
